### ISSUE TITLE
Check if input is URL

### ISSUE THREAD

**Issue by camilstaps** [clean-cloogle/cloo.gl#1]
cloo.gl should not accept requests for shortening things that are not URLs.

**Comment by dopefishh** [comment]
Urls not starting with `#^https?://#i` are prefixed with `http://`. This is already very restricting. I would like to add other protocols such as `irc`, `ftp`, `mailto`, etc...
Maybe we can prefix the url with `http://` only if there is no protocol given.

**Comment by dopefishh** [comment]
Also, I think it is overkill to match the urls, it's the user's own fault if the url is incorrect. Matching a correct url requires an arcane regex

    (?i)\b((?:[a-z][\w-]+:(?:/{1,3}|[a-z0-9%])|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'".,<>?«»“”‘’]))

Regex is from: https://daringfireball.net/2010/07/improved_regex_for_matching_urls
